### ISSUE TITLE
Add a field for "other/opposite side"

### ISSUE THREAD

**Issue by manwaring** [the-fab-cube/flesh-and-blood-cards#156]
With Dynasty it was relatively easy to identify the opposite side of a card because it was either `name - invoke` or `invoke + name` but with mechanoid and the horrifying naming of Prism's aura it's now a little more complicated.

I think having a field for `Opposite Side Card Name` would help with this now and in the future

**Comment by luceleaftea** [comment]
I think this would be handled by the fact that they share card ids, yes?

I also have this issue open - I was not planning on adding DFC cards with the same card id to it, but I am open to discussion on it!

https://github.com/the-fab-cube/flesh-and-blood-cards/issues/147

**Comment by manwaring** [comment]
Yes, you're absolutely right it can be handled by the shared card Ids, I'm a little slow and going to blame it on repeat exposure to spoiler season.  Not even once!

**Comment by luceleaftea** [comment]
I am still not feeling the relief of it being basically over 😂
