### ISSUE TITLE
Scar for a Scar doesn't exist in RF in UPR

### ISSUE THREAD

**Issue by schubam** [the-fab-cube/flesh-and-blood-cards#157]
According to these pages, Scar for a Scar (UPR209, UPR210, UPR211) does not exist in RF in Uprising.

- https://fabtcg.com/collectors-centre/uprising/
- https://www.cardmarket.com/en/FleshAndBlood/Cards/Scar-for-a-Scar-Red/Versions

**Comment by luceleaftea** [comment]
Good catch! Updated develop with this fix, and will close this issue when it is merged into main.
