### ISSUE TITLE
Add Dynasty card data

### ISSUE THREAD

**Issue by luceleaftea** [the-fab-cube/flesh-and-blood-cards#159]

**Comment by tonywok** [comment]
Hi there, thanks for all your hard work. I'm curious to learn about your process to see if I can help in any way. Is this entry automated or manual?

**Comment by luceleaftea** [comment]
@tonywok It's all manual! Data entry has been primarily me, with a lot of help from @manwaring ever since Fabrary started using the data set. Data entry for Dynasty is pretty much all completed, pending a final data review from me now that I've had a week away from the data (and time to play with the cards in person haha). If you want to browse through it before I review and merge it in (hopefully tomorrow if I have time), you can check it out [here](https://github.com/the-fab-cube/flesh-and-blood-cards/tree/dynasty)! Otherwise there's a lot of open issues that could use attention 😄
