### ISSUE TITLE
Skullhorn Cold Foil and Rainbow Foil 

### ISSUE THREAD

**Issue by schubam** [the-fab-cube/flesh-and-blood-cards#166]
There seems to be an error in the official collector's centre with **Skullhorn** (CRU006).
It seems to exist in Cold Foil and Non Foil in First, Rainbow Foil and Non Foil in Unlimited.

- https://www.cardmarket.com/en/FleshAndBlood/Cards/Skullhorn/Versions
- https://fabtcg.com/collectors-centre/crucible-of-war/

Please change 
```S - 1HP009 - N, S R - CRU006 - F, S R - CRU006 - U```

to 
```S - 1HP009 - N, S C - CRU006 - F, S R - CRU006 - U```

**Comment by luceleaftea** [comment]
Thank you so much for your detailed bug report! This is fixed in [v4.2.1](https://github.com/the-fab-cube/flesh-and-blood-cards/releases/tag/v4.2.1).
