### ISSUE TITLE
Kano, Dracai of Aether is only Non Foil in CRU

### ISSUE THREAD

**Issue by schubam** [the-fab-cube/flesh-and-blood-cards#167]
**Kano, Dracai of Aether** only in Non Foil in CRU-F and CRU-U.

- https://fabtcg.com/collectors-centre/crucible-of-war/
- https://www.cardmarket.com/en/FleshAndBlood/Cards/Kano-Dracai-of-Aether/Versions

Please change 
```
C - HER012 - N, R - HER020 - N, G - WIN008 - N, S - 1HP301 - N, S - ARC113 - F, S - ARC113 - U, S R - CRU158 - F, S R - CRU158 - U
```

to
```
C - HER012 - N, R - HER020 - N, G - WIN008 - N, S - 1HP301 - N, S - ARC113 - F, S - ARC113 - U, S - CRU158 - F, S - CRU158 - U
```

**Comment by luceleaftea** [comment]
Thank you so much for your detailed bug report! This is fixed in [v4.2.1](https://github.com/the-fab-cube/flesh-and-blood-cards/releases/tag/v4.2.1).
