### ISSUE TITLE
Alpha: WTR024 (Pack Hunt yellow) has no listing for non Foil

### ISSUE THREAD

**Issue by schubam** [the-fab-cube/flesh-and-blood-cards#169]
WTR024 (Pack Hunt yellow) has no listing for non Foil.

- https://www.cardmarket.com/en/FleshAndBlood/Cards/Pack-Hunt-Yellow/Versions
- https://fabtcg.com/collectors-centre/welcome-rathe/

Change
```
S - 1HP026 - N, R - WTR024 - A, S R - WTR024 - U
```

to
```
S - 1HP026 - N, S R - WTR024 - A, S R - WTR024 - U
```

**Comment by luceleaftea** [comment]
Thank you so much for your detailed bug report! This is fixed in [v4.2.1](https://github.com/the-fab-cube/flesh-and-blood-cards/releases/tag/v4.2.1).
