### ISSUE TITLE
Remove reminder text from all functional text

### ISSUE THREAD

**Issue by luceleaftea** [the-fab-cube/flesh-and-blood-cards#199]
Reminder text can frequently become outdated with CR updates, and it would be cleaner to just provide the current text, and have rulings be added later

**Comment by dcollinsn** [comment]
Concur, especially there are a lot of cards with outdated and incorrect text for Runechant tokens.

**Comment by PvtVoid** [comment]
I've pushed the data with removed reminder text. Quicken and Runechant are good example, but also Snag was a great one.

`Attack action cards can't gain {p} from their own effects, or the effects of attack reaction cards this turn. *(This only affects {p} that would be gained after Snag has resolved.)*`

Here's the pull request: https://github.com/the-fab-cube/flesh-and-blood-cards/pull/203

**Comment by luceleaftea** [comment]
Closed by #215
