### ISSUE TITLE
Mask of Perdition type mispelling

### ISSUE THREAD

**Issue by manwaring** [the-fab-cube/flesh-and-blood-cards#229]
Type text is `Assasin Equipment – Head` should be `Assassin Equipment – Head`

**Comment by gre99ory** [comment]
I would like to do it, to test the github flow

**Comment by luceleaftea** [comment]
@gre99ory go for it! 😄

**Comment by gre99ory** [comment]
Looks like someone already solved the issue ! Nothing to be done

**Comment by luceleaftea** [comment]
Thank you still for the offer to help!
