### ISSUE TITLE
[Feature request] Expand JSON printings to be per-foiling, not per-image

### ISSUE THREAD

**Issue by manwaring** [the-fab-cube/flesh-and-blood-cards#238]
Currently card printings are grouped based on common images, for e.g. this printing for Crown of Dominion covers both the Rainbow and Cold Foil treatments
```
{
  "unique_id": "AAA",
  "set_edition_unique_id": "BBB",
  "id": "DYN234",
  "set_id": "DYN",
  "edition": "N",
  "foilings": [
    "R",
    "C"
  ],
  "rarity": "L",
  "artist": "Andy Aslamov",
  "art_variation": null,
  "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-DYN/EN/DYN234.png"
}
```

This works well for displaying images, but isn't the right unit of printing for things like collection management and affiliate links - both of which consider printings to be unique based on Foilings as well.

The proposed data model is
```
{
  "unique_id": "AAA",
  "set_edition_unique_id": "BBB",
  "id": "DYN234",
  "set_id": "DYN",
  "edition": "N",
  "foiling": "R",
  "rarity": "L",
  "artist": "Andy Aslamov",
  "art_variation": null,
  "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-DYN/EN/DYN234.png"
},
{
  "unique_id": "CCC",
  "set_edition_unique_id": "DDD",
  "id": "DYN234",
  "set_id": "DYN",
  "edition": "N",
  "foiling": "C",
  "rarity": "L",
  "artist": "Andy Aslamov",
  "art_variation": null,
  "image_url": "https://storage.googleapis.com/fabmaster/cardfaces/2022-DYN/EN/DYN234.png"
}
```

While this does duplicate the portion of the data that is consistent between foilings, it would allow us for e.g. to add TCGP/CardMarket/etc. affiliate link mappings directly into the data set so that all developers using it can look up and pricing/inventory data in their apps.  It also works "out of the box" for any tools doing collection management or other features that need to treat foilings as different printings.

**Comment by luceleaftea** [comment]
This should be handled (as of awhile ago 😂 )
