### ISSUE TITLE
Silversheen Needle has a typoed card type

### ISSUE THREAD

**Issue by dcollinsn** [the-fab-cube/flesh-and-blood-cards#346]
In card.json, Silversheen Needle has type "Off-hand". Every other off-hand has type "Off-Hand". In type.json, only "Off-Hand" is listed as a valid choice for card types.

**Comment by luceleaftea** [comment]
Oops, thanks Dan! I'll get that updated when I have some time tonight, and add type capitalization as something for the validator to check for

**Comment by luceleaftea** [comment]
This should be fixed in v3.6.1!
