### ISSUE TITLE
Should we add a boolean field to denote cards only found in the expansion slot?

### ISSUE THREAD

**Issue by theblang** [the-fab-cube/flesh-and-blood-cards#385]
I think the expansion slot started in Bright Lights (it's where the Tunic reprint would be). They're continuing that paradigm in Heavy Hitters. It would be handy to easily know if a card is one of those (and thus can't be used in limited formats for that set).

**Comment by luceleaftea** [comment]
I like it! I need to restructure a few more parts of the Card Printing data structure soon (how to handle the new and cursed perforated split tokens that have the same card IDs and how to denote if a printing's image needs to be rotated to be displayed upright), so I'll keep this in mind when I'm working on that!
