### ISSUE TITLE
Flattened card json references names not found in type json

### ISSUE THREAD

**Issue by pnelson5** [the-fab-cube/flesh-and-blood-cards#396]
Version 6.7.0

Files involved:
json.zip/english/card-flattened.json
json.zip/english/type.json

The file card-flattened.json references some Types by name that are not present in type.json

Cards impacted:
Banksy
Cintari Sellsword
Teklovossen, the Mechropotent
Evo Atom Breaker
Evo Battery Pack
(other evos)

Types not present in type.json:
Wrench
Mercenary
Evo

**Comment by luceleaftea** [comment]
Thank you for the heads up! I've fixed this in the develop branch and it will be included in the next release. Please let me know if you find any other issues!
