### ISSUE TITLE
Add LGS237-LGS247, LGS253-LGS257

### ISSUE THREAD

**Issue by torgeirl** [the-fab-cube/flesh-and-blood-cards#400]
Judging from FaBrary's Collection listings, the following promos are missing from the dataset:

- [Heavy Hitters Release Celebration](https://fabtcg.com/retailer-news/heavy-hitters-release-celebration-promos-faq/) (x6)
- [March 2024 Armory Kit](https://fabtcg.com/resources/digital-assets/armory-events/) (x5)
- April 2024 Armory Kit (x5)

**Comment by luceleaftea** [comment]
Release Celebration and March Armory Kit were already in the data set (Fabrary likely just hadn't pulled them in yet), but added April 2024 in - thanks for the heads up!
