### ISSUE TITLE
Yellow and Blue Bonds of Ancestry are still legal in CC

### ISSUE THREAD

**Issue by AlphSpirit** [the-fab-cube/flesh-and-blood-cards#425]
As per [https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-8-7-24/](https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-8-7-24/)

**Comment by luceleaftea** [comment]
Just checked, this was added back in commit `9e6b864685a15787ee4765446a44f1a2caba1242`. Closing this, but thanks for opening the issue!
