### ISSUE TITLE
There is no high voltage card

### ISSUE THREAD

**Issue by SmuwuthE** [the-fab-cube/flesh-and-blood-cards#444]
When you search up high voltage, you see Sigil of Conductivity, I can't find High Voltage anywhere

**Comment by luceleaftea** [comment]
Hey, thanks for the report! I'm seeing High Voltage in the CSVs + JSON on my end - which files are you looking at and on what branch?

**Comment by SmuwuthE** [comment]
Oh sorry I thought this was the way to report a bug to fabproxy.com, my apologies
